- name: DevOps Lab Setup
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Kind
      get_url:
        url: https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
        dest: /usr/local/bin/kind
        mode: '0755'
